changes:
  - changed-files:
      - any-glob-to-any-file:
          - "**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/actions/**"
          - ".github/file-filters.yml"
          - ".github/dependabot.yml"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"
          - "pnpm-workspace.yaml"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "test/**"
          - "src/**/*.test.ts"

app:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "nest-cli.json"
          - "drizzle.config.ts"
          - "drizzle/**"
          - "tsconfig*.json"
          - "vitest.config*.ts"
